### ISSUE TITLE
Missing interpreter shebang on the standalone ascii.py file, other small suggestions 

### ISSUE THREAD

**Issue by desrod** [AlexEidt/ASCII-Video#1]
Interesting project, testing it now, but were a initial speedbumps getting it working cleanly in a venv: 

1. No need for `--user` when using venv (the correct way to test/run this in an isolated way, since it's not packaged for install) 
2. Missing shebang in ascii.py for the intended python interpreter (eg: `#!/usr/bin/env python3`)
3. Install and run `black` on the code to reformat and lint it

**Comment by AlexEidt** [comment]
Thanks for the feedback. I've implemented all the changes you suggested. I've never used `black` before, however I'm glad I learned about it now. Great tool.
