### ISSUE TITLE
Host on PyPI?

### ISSUE THREAD

**Issue by paw-lu** [AlexEidt/ASCII-Video#2]
Cool work! I'm interested in testing out how it would work in [nbpreview](https://github.com/paw-lu/nbpreview).

For easier distribution, have you thought of hosting it on PyPI as a pip-installable package for easier distribution?

**Comment by AlexEidt** [comment]
Thanks! I did consider hosting on PyPI, but opted against it for the simplicity of just hosting the `.py` file here.
